### ISSUE TITLE
Rhythmbox wont start from the extension

### ISSUE THREAD

**Issue by WyRe** [eonpatapon/gnome-shell-extensions-mediaplayer#346] opened 2017-04-25 11:22 UTC
I cannot get Rhythmbox startup using the extension. I've setup Rhythmbox as my default player and marked "allow the starting of the default media player" in your extension but when I click on the extension Rhythmbox won't start

I'm running Gnome 3.24.1 in ArchLinux.

**Comment by JasonLG1979** [comment] 2017-04-25 12:05
I can confirm inconsistent behavior when I 1st set Rhythmbox as my default player. But if I logout and back in again or restart the Shell everything is as it should be. I think it has to do with how we find player desktop files and the fact that Rhythmbox has a bunch of different .desktop files for some reason?

**Comment by JasonLG1979** [comment] 2017-04-25 12:08
I thought about removing the "allow the starting of the default media player" altogether as it actually takes more clicks to open a player from the extension then it does from the dash/dock.

**Comment by JasonLG1979** [comment] 2017-04-25 20:47
I've got a PR in to remove the default player option. Just waiting for some feedback from @eonpatapon.

**Comment by WyRe** [comment] 2017-04-25 21:33
But I like that behavior/feature :(

**Comment by JasonLG1979** [comment] 2017-04-25 21:48
> But I like that behavior/feature :(
> 
> Or at least the feature to run the chosen music player by user.

That's why I didn't just merge it. I want feedback. But from a code standpoint it never really worked right to begin with. From this issue, to Amarok crashing the extensions if it's set as the default player, to inconsistent placement in the system menu when there are multiple other extensions in the system menu. Unless someone can fix all that(the Amarok bug got fixed but the fix causes your issue) it's just not worth the headache.

**Comment by JasonLG1979** [comment] 2017-04-25 21:50
I also don't like indicators being resident in panel or system menu. When they aren't actually doing anything they should be hidden IMHO.

**Comment by JasonLG1979** [comment] 2017-04-25 21:59
I also want to start focusing on code quality. I would like to remove as many "hacks" as I can from the extension and that feature relies on one such "hack". Ofc being a GNOME Shell extension there are a lot of hacks because extensions basically have no public API. To do pretty much anything with the Shell you have to deal with private-ish bit. (nothing is actually unreachable but vars that start with an underscore are generally considered implementation details that shouldn't be depended upon.)  It's really horrible. But the GNOME dev's don't seem to care that they break extensions with every release...

**Comment by WyRe** [comment] 2017-04-26 13:34
I've also noticed that slide position adjustment of the song doesn't load always (for each song).

**Comment by JasonLG1979** [comment] 2017-04-27 05:00
> I've also noticed that slide position adjustment of the song doesn't load always (for each song). At least in continuous playing (when Rhythmbox changes the song).

If the song's metadata doesn't contain a duration(mpris:length) or the player can't provide a position the position slider is hidden.

**Comment by WyRe** [comment] 2017-04-27 09:31
> If the song's metadata doesn't contain a duration(mpris:length) or the player can't provide a position the position slider is hidden.

How can I check that? I've used mediainfo tool to print my songs metadata and I get a value to 'Duration' but I don't know if this is `mpris:length` anyway ... apparently the songs contain metadata duration. 

```
mediainfo Zsak\ -\ Apocalypto\ \[Original\ Mix\]-EabbztSWN7M.opus 
E: File read error
General
Complete name                            : Zsak - Apocalypto [Original Mix]-EabbztSWN7M.opus
Format                                   : Ogg
File size                                : 8.73 MiB
Duration                                 : 7 min 12 s
Overall bit rate                         : 170 kb/s
Writing application                      : Lavf57.71.100

Audio
ID                                       : 3010080730 (0xB36A2FDA)
Format                                   : Opus
Duration                                 : 7 min 12 s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 kHz
Compression mode                         : Lossy
Writing library                          : Lavf57.71.100
Language                                 : English
```

**Comment by JasonLG1979** [comment] 2017-04-27 12:13
MPRIS metadata isn't the same as the metadata of the file that's being played. https://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/

The player is suppose to provide the metadata to MPRIS clients following the above spec.

**Comment by JasonLG1979** [comment] 2017-04-28 23:06
@WyRe I'm closing this because it references a feature that no longer exists.  Please start a new issue new issue about the position slider.

**Closed by JasonLG1979** 2017-04-28 23:06 UTC
