### ISSUE TITLE
Amarok causes indicator to crash.

### ISSUE THREAD

**Issue by knuthingmuch** [eonpatapon/gnome-shell-extensions-mediaplayer#267] opened 2016-06-11 11:30 UTC
![screenshot from 2016-06-11 16-48-44](https://cloud.githubusercontent.com/assets/17121944/16114267/f5b1ed4e-33dd-11e6-902a-59bcbbcdb271.png)
Amarok causes indicator to fail to load and/or crash.
..Steps to reproduce(GNOME Shell 3.18.4 and some earlier versions - first appeared in 3.14 IIRC):
..1)Install media player indicator from extensions.gnome.org
..2)apt-get install amarok (works fine at this point)
..3)restart gnome-shell/login again.
..4)Looking glass shows error as "this.app is null"
.....Tweak Tool->Extensions->Media player indicator->"error loading extension"
..5)apt-get remove amarok
..6)restart gnome-shell
.....Media player indicator works.
Subsequently making any change to panel, makes indicator crash.

**Comment by knuthingmuch** [comment] 2016-06-19 16:56
Update: In Shell 3.18.5, additional Error message shows up-"manager is not defined".
![screenshot from 2016-06-19 22-25-07](https://cloud.githubusercontent.com/assets/17121944/16178669/b6e0a614-366c-11e6-95a1-2983db0be8f1.png)

**Comment by JasonLG1979** [comment] 2016-11-26 10:14
I know this is old but I can reproduce it in 3.22 by install Amarok and setting it as my default audio player.

It seems to be a bug on Amarok's side, their DBus name doesn't match their object path.

Here's Amarok in D-Feet:
![screenshot from 2016-11-26 03-59-07](https://cloud.githubusercontent.com/assets/6667703/20639585/6dabc3fe-b38d-11e6-9e6d-1b7d1b71aa19.png)

Notice "Name: org.kde.amarok" doesn't equal the 1st object path

Where as here is Totem:

![screenshot from 2016-11-26 03-59-50](https://cloud.githubusercontent.com/assets/6667703/20639613/02836342-b38e-11e6-8049-3d1b9cb87100.png)

The Name matches the object path.


I'm not sure who's wrong or right GNOME or KDE but I'd file a bug with Amarok and see where that gets you maybe?

**Comment by knuthingmuch** [comment] 2016-11-26 11:36
Thanks a lot Jason. 
It appears that this name mismatch exists for all kde apps, not just Amarok so I'm a bit wary of filing a bug report. I'll look around a bit more before I do that. In the meantime setting any app(other than Amarok) as the default music player seems to be a good workaround.

**Comment by knuthingmuch** [comment] 2016-11-26 12:53
Filtered Dbus logs recorded during gnome shell restart. ":1.47" is unique name of Amarok.
First one is without amarok as default music app; second is with.

[log0_1.47.txt](https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/files/614227/log0_1.47.txt)
[log1_1.47.txt](https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/files/614228/log1_1.47.txt)

**Comment by JasonLG1979** [comment] 2016-11-26 15:09
> It appears that this name mismatch exists for all kde apps

I seem to remember reading that somewhere.

The bug happens here:
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/blob/master/src/ui.js#L96-L98

Gio.app_info_get_default_for_type('audio/x-vorbis+ogg', false).get_id() returns something like org.gnome.Totem.desktop for example for Totem, which works fine. And just amarok.desktop for Amarok. Which does not work and causes Shell.AppSystem.get_default().lookup_app to fail.

**Comment by JasonLG1979** [comment] 2016-11-26 15:33
On an unrelated note:
@eonpatapon 

https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/blob/master/src/ui.js#L99

Seems to declare a block scope local variable "appInfo" which doesn't seem to ever be used anywhere?

**Comment by knuthingmuch** [comment] 2016-11-26 15:50
That explains...Thanks! 
As a better workaround; disabling "Allow to start the default media player" in extension settings solves the problem for all practical purposes.

**Comment by JasonLG1979** [comment] 2016-11-26 17:00
It's not a Debian/Ubuntu specific problem. I'm running Fedora 25 and I still get the error.

Another quick and dirty fix is to make sure the return value of Gio.app_info_get_default_for_type has 3 "."s in it:

```js
      let appId = Gio.app_info_get_default_for_type('audio/x-vorbis+ogg', false).get_id()
      if (appId.replace(/[^.]/g, "").length < 3) {
        return;
      }
      this.app = Shell.AppSystem.get_default().lookup_app(appId));
```

Otherwise just return and no default app shows up.

**Comment by JasonLG1979** [comment] 2016-11-26 18:42
@knuthingmuch 

> so that the Gio method searches for desktop files recursively?

I'm pretty new to js but bits in this little python3 script may be able to adapted to solve the problem. It does a manual search of desktop files.

```python

from gi.repository import Gio

app_id = Gio.app_info_get_default_for_type('audio/x-vorbis+ogg', False).get_id()
for word in app_id.replace('.desktop', '').split('.'):
    search_results = Gio.DesktopAppInfo.search(word)
    if search_results:
        embedded_list = search_results[0]
        for result in embedded_list:
            if app_id == result:
                break
            else:
                app_id = embedded_list[0]
print(app_id)
```

for Amarok it prints "kde4-amarok.desktop" . And for Totem it prints the "org.gnome.Totem.desktop".

if I do this:

```js
this.app = Shell.AppSystem.get_default().lookup_app("kde4-amarok.desktop"));
```

It works as expected and the extension doesn't crash. I just need to figure out how to translate it to js,lol!!!

**Comment by knuthingmuch** [comment] 2016-11-26 19:07
Hmm..that's a pretty neat fix. I barely know any JS..and even less about gnome extension scripting, so I guess you're the A-team. 
This seems to be an interoperability problem that should ideally solved within the respective libraries. I tried going through the glib library, the relevant code is a daisy chain of functions; eventually I tired of going through it all, and not having hacked a library before decided to call it quits. If you're interested take a look at:
https://github.com/GNOME/glib/blob/master/gio/gdesktopappinfo.c
and possibly:
https://github.com/GNOME/glib/blob/master/glib/gutils.c

**Comment by JasonLG1979** [comment] 2016-11-26 19:53
> Hmm..that's a good fix but still feels a bit "band-aidy".

It's very "band-aidy" and shouldn't be necessary. If I remember correctly it's a known bug but neither KDE nor GNOME is willing to compromise so we all loose.

Here is a working band-aid in js:
```js
      let appInfo = Gio.app_info_get_default_for_type("audio/x-vorbis+ogg", false);
      let appId = appInfo.get_id();
      let appName = appInfo.get_name();
      let gioSearchResults = Gio.DesktopAppInfo.search(appName);
      if (gioSearchResults) {
          for (let result in gioSearchResults[0]) {
            if (appId === result) {
              break;
            }
            else {
              appId = gioSearchResults[0][0];
            }
          }
        }

      this.app = Shell.AppSystem.get_default().lookup_app(appId);
```

**Comment by knuthingmuch** [comment] 2016-11-26 19:59
> If I remember correctly it's a known bug but neither KDE nor GNOME is willing to compromise so we all loose. 
Too bad. 
Anyways..good work @JasonLG1979, I admire your persistence.

**Comment by JasonLG1979** [comment] 2016-11-26 20:00
I'll test it for a while with a bunch a players and if it works I'll put in a PR.

**Comment by JasonLG1979** [comment] 2016-11-26 20:24
Hey @badcel and/or @eonpatapon your thought on this? It works for Lollypop, Totem, and Amarok. You want to give it a test on your preferred players?

**Comment by JasonLG1979** [comment] 2016-11-27 00:58
@knuthingmuch and anyone else interested could you please test:
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/tree/fix-resolving-kde-desktop-files

**Comment by knuthingmuch** [comment] 2016-11-28 08:20
I works on Shell 3.18.5 with Amarok and Rhythmbox as default players.

**Closed** 2016-12-09 09:50 UTC
