### ISSUE TITLE
Close button and sound control

### ISSUE THREAD

**Issue by gogi983** [eonpatapon/gnome-shell-extensions-mediaplayer#215] opened 2015-10-16 11:23 UTC
Hello,

Since last upgrade, the close button in extension disappeared... Is this a bug or has it simply been removed from?

And second question which is more a request than an issue : is it possible for you to separate volume control of the app from volume control of the system...
I mean, I am on Debian/Gnome and I would like to control the volume of the application from the extension without changing volume level in the aggregate menu.
If it is a mess to add this globally in your extension for all users, can you tell me please what should I do add on my own a as custom change?

Greetings

**Comment by eonpatapon** [comment] 2015-10-16 11:43
Hello,

Yes the close button is gone. Actually I didn't find any place for it in the new design.

The volume control is supposed to be separate from the system volume. It just changes the volume of the player. I don't know exactly why but players that use gstreamer will modify the system volume when the volume of the app is changed (for example lollypop). If you try Clementine for example, only the volume of clementine should change not the system volume.

**Comment by gogi983** [comment] 2015-10-16 11:54
Well is there any way to get it back in further upgrade? (mean close button).

Yes that's what I was expecting for a time ago, and when I did last upgrade it finally worked, but only a few minutes until I rebooted, and now it's not working anymore. I'm using VLC and that"s right it depends on gstreamer. It's a real issue because if more than one application change volume, volume control becomes absolutely not synchronised anymore. I.e. in VLC, if I change volume on app, then change again in aggregate menu, and so on some more times, after a while volume level in VLC may be at 20% while in aggregate menu it will be at 60% or vice versa.
Some months ago I made some research in order to try to solve this by myself, and I figured out it may be in relation with Pulse-audio too, but my competencies in that domain are very limited.

**Comment by badcel** [comment] 2015-10-16 22:30
I think the problem is due to configuration in pulse audio. In /etc/pulse/daemon.con there is a setting called "flat-volumes". If you disable it ("flat-volumes=no") pulseaudio is not adjusting multiple sound sources at once.

**Comment by JasonLG1979** [comment] 2017-01-31 14:04
@gogi983 have you resolved you audio issues? As far as a close button, I've done another redesign and still have yet to find a good place for a close button.

**Comment by gogi983** [comment] 2017-01-31 14:46
Hi @JasonLG1979 ,
Actually I totally forgot about this request until you answered right now. To answer your question, yes audio issues are solved, I can't tell if it was by upgrading the extension or something else on my distribution, but it's working nice and smooth now (by the way I'm on Debian Sid).

To  be more precise, the behaviour is the following : 

- if system volume is higher than extension's one, then lowering system volume even under extension's one will lower both of them.
- if extension's volume is lower than system's one, then increasing extension's volume over system's one will increase both of them.
- if you put system's volume at 100% and change extension's one only, then it will work fine in system's volume area (0-100%) without affecting it.

The only problem is that if you put volume in the extension at 40%, and system's one at more than that (60, 70, 80%... in example), then lowering system's volume will lower extension's one too. That's a misbehaviour, they should be totally independant from each other, given that system's sound control has to behave like master.

Sorry for my english, it isn't that perfect and I hope you understand what I mean.

**Comment by JasonLG1979** [comment] 2017-01-31 16:05
> they should be totally independant from each other, given that system's sound control has to behave like master.

They are totally independent. We don't change the system volume in any way directly. All we do is tell the player to change it's volume. What it does to the volume either it's own or the system's volume it totally up to the app.

**Comment by JasonLG1979** [comment] 2017-01-31 16:09
But as badcel has said, your pulseaudio configuration can effect how volumes work in pulseaudio. To reiterate. We do not change the system volume.

**Comment by JasonLG1979** [comment] 2017-01-31 16:11
I suspect pulseaudio is misconfigured on your system.

**Comment by JasonLG1979** [comment] 2017-01-31 16:17
@gogi983 I'm going to close this issue because it's really 2 issues. 1. The missing close button, which if you'd like please feel free to open a new seperate issue just for that. And 2. The audio issue, which is invalid.

**Closed by JasonLG1979** 2017-01-31 16:17 UTC
Labels: design
