### ISSUE TITLE
make install-zip doesn't work on ubuntu gnome xenial

### ISSUE THREAD

**Issue by DwordPtr** [eonpatapon/gnome-shell-extensions-mediaplayer#282] opened 2016-11-13 04:20 UTC
I'm on xenial. After installing the gnome common script from apt I run make install-zip and I've got the error message. `Making all in src
make[1]: Entering directory '/home/bryan/configs/gnome-shell-extensions-mediaplayer/src'
Makefile:501: *** missing separator.  Stop.
make[1]: Leaving directory '/home/bryan/configs/gnome-shell-extensions-mediaplayer/src'
Makefile:350: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1` 

I may just try a global install since I'm on a one user system.
This project looks great media integration is one of the few things I miss from unity.

**Comment by JasonLG1979** [comment] 2017-01-28 09:36
@DwordPtr did you ever resolve this issue?

**Comment by JasonLG1979** [comment] 2017-04-01 22:16
I'm going to assume the issue has been resolved @DwordPtr since you have not responded. I'm closing this.

**Closed by JasonLG1979** 2017-04-01 22:16 UTC
Labels: more info needed

**Comment by heinzdmx** [comment] 2017-04-05 21:47
In case anyone may find this issue. I had the same issue that was caused by not having glib 2 installed
Fixed it by issuing 
`# sudo apt-get install libglib2.0-dev automake gnome-common gettext`
